import { Product } from "@/types";
import { slugify } from "@/lib/db";
export function getPrintifyConfig(settings:any){ const c=settings?.integrations?.printify||{}; return {enabled:Boolean(c.enabled),apiToken:c.apiToken||"",shopId:c.shopId||"",useAsProductSource:c.useAsProductSource!==false,autoSubmitOrders:c.autoSubmitOrders!==false}; }
function h(c:any){ if(!c.apiToken) throw new Error("Printify API Token em falta."); return {Authorization:`Bearer ${c.apiToken}`,"Content-Type":"application/json"}; }
async function pi(c:any,path:string,init?:RequestInit){ const res=await fetch(`https://api.printify.com/v1${path}`,{...init,headers:{...h(c),...(init?.headers||{})},cache:"no-store"}); const data=await res.json().catch(()=>({})); if(!res.ok) throw new Error(data?.message||data?.error||`Erro Printify: ${res.status}`); return data; }
function price(cents:number,settings:any){ const base=Number(cents||0)/100; if(settings?.pricing?.mode==="margin") return Number((base*(1+Number(settings?.pricing?.marginPercent||40)/100)).toFixed(2)); return base; }
export async function queryPrintifyShops(config:any){ return await pi(config,"/shops.json"); }
export async function queryPrintifyProducts(config:any, settings:any):Promise<Product[]>{ if(!config.shopId) throw new Error("Printify Shop ID em falta."); const data=await pi(config,`/shops/${config.shopId}/products.json`); const list=data.data||[]; return list.map((p:any)=>{ const v=(p.variants||[]).find((x:any)=>x.is_enabled)||p.variants?.[0]||{}; const images=(p.images||[]).map((x:any)=>x.src).filter(Boolean); const title=p.title||"Printify product"; return {id:`printify-${p.id}`,slug:slugify(title),title,categoryId:"",category:"",collection:"",gender:"unisex",style:"printify",price:price(v.price||0,settings),compareAt:0,cost:Number(v.cost||0)/100,stock:v.is_enabled?999:0,source:"printify",status:p.visible===false?"draft":"active",image:images[0]||"https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1200&auto=format&fit=crop",mediaType:"image",gallery:images,description:p.description||"Produto print-on-demand produzido e enviado pela Printify.",details:["Produção sob encomenda","Envio pela Printify"],colors:[],sizes:[],tags:["printify"],provider:"printify",providerProductId:String(p.id),providerVariantId:v.id?String(v.id):"",printifyProductId:String(p.id),printifyVariantId:v.id?String(v.id):""} as Product; }); }
export async function testPrintifyConnection(config:any){ const shops=await queryPrintifyShops(config); return {ok:true,count:shops.length,shops}; }


